version: '3.0'

services:

    node:
        image: node:12
        container_name: puppeteer-node-app
        working_dir: /app
        volumes:
            - /data/www/site/comic.pre.hlzblog.top:/app:cached # 重要！！！ 此部分请依据自己的项目位置 进行调整
            - ../apt_image.txt:/etc/apt/sources.list
            - /tmp/comic_node:/app/storage/log
        ports:
            - 7070:7070
        environment:
            TZ: Asia/Shanghai
            NODE_ENV: production
        networks:
            default:
                ipv4_address: 172.28.0.2
        #command:  bash -c "export TERM=xterm && cd /app && make install && make www"
        command:  bash -c "export TERM=xterm && cd /app && tail -f"

networks:
    default:
        external:
            name: network_unix
